# Generated by Django 4.2.1 on 2023-05-31 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0002_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'registration',
            },
        ),
    ]
