# Generated by Django 4.2.1 on 2023-05-31 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0003_registration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registration',
        ),
    ]
